---
$schema: http://json-schema.org/draft-04/schema

definitions:
    # base types
    param:
        oneOf:
        - type: object
          properties:
            get_param:
                type: string
          additionalProperties: False
        - type: object
          properties:
            get_input:
                type: string
          additionalProperties: False
    string_or_param:
        oneOf:
          - type: string
          - $ref: "#/definitions/param"
    int_or_param:
        oneOf:
          - type: integer
          - $ref: "#/definitions/param"
    bool_or_param:
        oneOf:
          - type: boolean
          - # also accept strings of boolean values (like oslo_utils.strutils)
            type: string
            pattern: "(?i)^(t|True|true|on|y|yes|1|f|False|false|off|n|no|0)$"
          - $ref: "#/definitions/param"
    # MAC address type
    mac_address_string:
        type: string
        pattern: "^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$"
    # IP address and address+prefix types
    ipv4_address_string:
        type: string
        pattern: "^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).){3}\
            (25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"
    ipv6_address_string:
        type: string
        pattern: "^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}\
            |([0-9a-fA-F]{1,4}:){1,7}:\
            |([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}\
            |([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}\
            |([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}\
            |([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}\
            |([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}\
            |[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})\
            |:((:[0-9a-fA-F]{1,4}){1,7}|:))$"
    ip_address_string:
        oneOf:
          - $ref: "#/definitions/ipv4_address_string"
          - $ref: "#/definitions/ipv6_address_string"
    ip_address_string_or_param:
        oneOf:
          - $ref: "#/definitions/ip_address_string"
          - $ref: "#/definitions/param"
    list_of_ip_address_string_or_param:
        oneOf:
          - type: array
            items:
                $ref: "#/definitions/ip_address_string_or_param"
            minItems: 0
          - $ref: "#/definitions/param"

    ipv4_cidr_string:
        type: string
        pattern: "^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).){3}\
            (25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\
            /(3[0-2]|[1-2][0-9]|[0-9])$"
    ipv6_cidr_string:
        type: string
        pattern: "^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}\
            |([0-9a-fA-F]{1,4}:){1,7}:\
            |([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}\
            |([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}\
            |([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}\
            |([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}\
            |([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}\
            |[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})\
            |:((:[0-9a-fA-F]{1,4}){1,7}|:))\
            /(12[0-8]|1[0-1][0-9]|[1-9][0-9]|[0-9])$"
    ip_cidr_string:
        oneOf:
          - $ref: "#/definitions/ipv4_cidr_string"
          - $ref: "#/definitions/ipv6_cidr_string"
    ip_cidr_string_or_param:
        oneOf:
          - $ref: "#/definitions/ip_cidr_string"
          - $ref: "#/definitions/param"
          - type: object
            properties:
                list_join:
                    type: array
                    items:
                      - enum: ["/"]
                      - type: array
                        items:
                          - $ref: "#/definitions/ip_address_string_or_param"
                          - $ref: "#/definitions/int_or_param"
            required:
                - list_join
            additionalProperties: False
    domain_name_string:
        type: string
        pattern: >-
          ^(?=^.{1,255}$)(?!.*\.\..*)(.{1,63}\.)+(.{0,63}\.?)|(?!\.)(?!.*\.\..*)(^.{1,63}$)|(^\.$)$

    list_of_domain_name_string_or_domain_name_string:
        oneOf:
          - type: array
            items:
                $ref: "#/definitions/domain_name_string"
            minItems: 0
          - $ref: "#/definitions/domain_name_string"

    # os-net-config derived types
    address:
        type: object
        properties:
            ip_netmask:
                $ref: "#/definitions/ip_cidr_string_or_param"
        required:
          - ip_netmask
        additionalProperties: False
    list_of_address:
        type: array
        items:
            $ref: "#/definitions/address"
        minItems: 1

    route:
        type: object
        oneOf:
        - properties:
            next_hop:
                $ref: "#/definitions/ip_address_string_or_param"
            ip_netmask:
                $ref: "#/definitions/ip_cidr_string_or_param"
            default:
                $ref: "#/definitions/bool_or_param"
            route_options:
                $ref: "#/definitions/string_or_param"
            table:
                anyOf:
                    - $ref: "#/definitions/string_or_param"
                    - $ref: "#/definitions/int_or_param"
          requires:
            - next_hop
          additionalProperties: False
        - properties:
            nexthop:
                $ref: "#/definitions/ip_address_string_or_param"
            destination:
                $ref: "#/definitions/ip_cidr_string_or_param"
            default:
                $ref: "#/definitions/bool_or_param"
            route_options:
                $ref: "#/definitions/string_or_param"
            table:
                anyOf:
                    - $ref: "#/definitions/string_or_param"
                    - $ref: "#/definitions/int_or_param"
          requires:
            - nexthop
          additionalProperties: False
    list_of_route:
        type: array
        items:
            $ref: "#/definitions/route"
        minItems: 0

    route_rule:
        type: object
        properties:
            rule:
                $ref: "#/definitions/string_or_param"
            comment:
                $ref: "#/definitions/string_or_param"
        required:
          - rule
        additionalProperties: False
    list_of_rule:
        type: array
        items:
            $ref: "#/definitions/route_rule"
        minItems: 1

    nic_mapping:
        type: ["object", "null"]

    ovs_options_string:
        type: string
        pattern: "^((?:[a-zA-Z][a-zA-Z0-9: _-]*)=(?:[a-zA-Z0-9:._-]+)[ ]*)+$"

    ovs_options_string_or_param:
        oneOf:
          - $ref: "#/definitions/ovs_options_string"
          - $ref: "#/definitions/param"

    ovs_extra_string:
        type: string

    ovs_extra:
        oneOf:
          - $ref: "#/definitions/ovs_extra_string"
          - type: array
            items:
                $ref: "#/definitions/ovs_extra_string"
            minItems: 1

    ovs_extra_or_param:
        oneOf:
          - $ref: "#/definitions/ovs_extra"
          - $ref: "#/definitions/param"

    # os-net-config device types
    interface:
        type: object
        properties:
            type:
                enum: ["interface"]
            name:
                $ref: "#/definitions/string_or_param"
            hwaddr:
                $ref: "#/definitions/mac_address_string"
            primary:
                $ref: "#/definitions/bool_or_param"
            ethtool_opts:
                $ref: "#/definitions/string_or_param"
            hotplug:
                $ref: "#/definitions/bool_or_param"
            # common options:
            use_dhcp:
                $ref: "#/definitions/bool_or_param"
            use_dhcpv6:
                $ref: "#/definitions/bool_or_param"
            addresses:
                $ref: "#/definitions/list_of_address"
            routes:
                $ref: "#/definitions/list_of_route"
            rules:
                $ref: "#/definitions/list_of_rule"
            mtu:
                $ref: "#/definitions/int_or_param"
            access_point: 
                $ref: "#/definitions/bool_or_param"
            nic_mapping:
                $ref: "#/definitions/nic_mapping"
            persist_mapping:
                $ref: "#/definitions/bool_or_param"
            defroute:
                $ref: "#/definitions/bool_or_param"
            dhclient_args:
                $ref: "#/definitions/string_or_param"
            dns_servers:
                $ref: "#/definitions/list_of_ip_address_string_or_param"
            nm_controlled:
                $ref: "#/definitions/bool_or_param"
            onboot:
                $ref: "#/definitions/bool_or_param"
            domain:
                $ref: "#/definitions/list_of_domain_name_string_or_domain_name_string"
            alias:
                $ref: "#/definitions/string_or_param"
            orig_name:
                $ref: "#/definitions/string_or_param"
            pci_address:
                $ref: "#/definitions/string_or_param"
            linkdelay:
                $ref: "#/definitions/int_or_param"
        required:
          - type
          - name
        additionalProperties: True

    route_table:
        type: object
        properties:
            type:
                enum: ["route_table"]
            name:
                $ref: "#/definitions/string_or_param"
            table_id:
                anyOf:
                  - $ref: "#/definitions/int_or_param"
                  - $ref: "#/definitions/string_or_param"
        required:
          - type
          - name
          - table_id
        additionalProperties: False

    vlan:
        type: object
        properties:
            type:
                enum: ["vlan"]
            vlan_id:
                $ref: "#/definitions/int_or_param"
            device:
                $ref: "#/definitions/string_or_param"
            primary:
                $ref: "#/definitions/bool_or_param"
            # common options:
            use_dhcp:
                $ref: "#/definitions/bool_or_param"
            use_dhcpv6:
                $ref: "#/definitions/bool_or_param"
            addresses:
                $ref: "#/definitions/list_of_address"
            routes:
                $ref: "#/definitions/list_of_route"
            rules:
                $ref: "#/definitions/list_of_rule"
            mtu:
                $ref: "#/definitions/int_or_param"
            nic_mapping:
                $ref: "#/definitions/nic_mapping"
            persist_mapping:
                $ref: "#/definitions/bool_or_param"
            defroute:
                $ref: "#/definitions/bool_or_param"
            dhclient_args:
                $ref: "#/definitions/string_or_param"
            dns_servers:
                $ref: "#/definitions/list_of_ip_address_string_or_param"
            nm_controlled:
                $ref: "#/definitions/bool_or_param"
            onboot:
                $ref: "#/definitions/bool_or_param"
            domain:
                $ref: "#/definitions/list_of_domain_name_string_or_domain_name_string"
            alias:
                $ref: "#/definitions/string_or_param"
            ovs_options:
                $ref: "#/definitions/ovs_options_string_or_param"
            ovs_extra:
                $ref: "#/definitions/ovs_extra_or_param"
        required:
          - type
          - vlan_id
        additionalProperties: True

    ovs_bridge:
        type: object
        properties:
            type:
                enum: ["ovs_bridge"]
            name:
                $ref: "#/definitions/string_or_param"
            members:
                type: array
                items:
                    oneOf:
                      - $ref: "#/definitions/interface"
                      - $ref: "#/definitions/vlan"
            ovs_options:
                $ref: "#/definitions/ovs_options_string_or_param"
            ovs_extra:
                $ref: "#/definitions/ovs_extra_or_param"
            ovs_fail_mode:
                $ref: "#/definitions/ovs_fail_mode_or_param"
            # common options:
            use_dhcp:
                $ref: "#/definitions/bool_or_param"
            use_dhcpv6:
                $ref: "#/definitions/bool_or_param"
            addresses:
                $ref: "#/definitions/list_of_address"
            routes:
                $ref: "#/definitions/list_of_route"
            rules:
                $ref: "#/definitions/list_of_rule"
            mtu:
                $ref: "#/definitions/int_or_param"
            nic_mapping:
                $ref: "#/definitions/nic_mapping"
            persist_mapping:
                $ref: "#/definitions/bool_or_param"
            defroute:
                $ref: "#/definitions/bool_or_param"
            dhclient_args:
                $ref: "#/definitions/string_or_param"
            dns_servers:
                $ref: "#/definitions/list_of_ip_address_string_or_param"
            nm_controlled:
                $ref: "#/definitions/bool_or_param"
            onboot:
                $ref: "#/definitions/bool_or_param"
            domain:
                $ref: "#/definitions/list_of_domain_name_string_or_domain_name_string"
        required:
          - type
          - name
          - members
        additionalProperties: False

    linux_bridge:
        type: object
        properties:
            type:
                enum: ["linux_bridge"]
            name:
                $ref: "#/definitions/string_or_param"
            members:
                type: array
                items:
                    oneOf:
                      - $ref: "#/definitions/interface"
                      - $ref: "#/definitions/vlan"
            # common options:
            use_dhcp:
                $ref: "#/definitions/bool_or_param"
            use_dhcpv6:
                $ref: "#/definitions/bool_or_param"
            addresses:
                $ref: "#/definitions/list_of_address"
            routes:
                $ref: "#/definitions/list_of_route"
            rules:
                $ref: "#/definitions/list_of_rule"
            mtu:
                $ref: "#/definitions/int_or_param"
            nic_mapping:
                $ref: "#/definitions/nic_mapping"
            persist_mapping:
                $ref: "#/definitions/bool_or_param"
            defroute:
                $ref: "#/definitions/bool_or_param"
            dhclient_args:
                $ref: "#/definitions/string_or_param"
            dns_servers:
                $ref: "#/definitions/list_of_ip_address_string_or_param"
            nm_controlled:
                $ref: "#/definitions/bool_or_param"
            onboot:
                $ref: "#/definitions/bool_or_param"
            domain:
                $ref: "#/definitions/list_of_domain_name_string_or_domain_name_string"
            alias:
                $ref: "#/definitions/string_or_param"
        required:
          - type
          - name
          - members
        additionalProperties: True

type: array
items:
    oneOf:
      - $ref: "#/definitions/interface"
      - $ref: "#/definitions/route_table"
      - $ref: "#/definitions/vlan"
      - $ref: "#/definitions/linux_bridge"
      - $ref: "#/definitions/ovs_bridge"
minItems: 1
